/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CertificatRouteImport } from './routes/certificat'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as MissionsRouteImport } from './routes/missions'
import { Route as MissionsIndexRouteImport } from './routes/missions.index'
import { Route as MissionsIdRouteImport } from './routes/missions.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CertificatRoute = CertificatRouteImport.update({
  id: '/certificat',
  path: '/certificat',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsRoute = MissionsRouteImport.update({
  id: '/missions',
  path: '/missions',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionsIndexRoute = MissionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MissionsRoute,
} as any)
const MissionsIdRoute = MissionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => MissionsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/certificat': typeof CertificatRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/missions': typeof MissionsRouteWithChildren
  '/missions/$id': typeof MissionsIdRoute
  '/missions/': typeof MissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/certificat': typeof CertificatRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/missions/$id': typeof MissionsIdRoute
  '/missions': typeof MissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/certificat': typeof CertificatRoute
  '/connexion': typeof ConnexionRoute
  '/inscription': typeof InscriptionRoute
  '/missions': typeof MissionsRouteWithChildren
  '/missions/$id': typeof MissionsIdRoute
  '/missions/': typeof MissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/certificat'
    | '/connexion'
    | '/inscription'
    | '/missions'
    | '/missions/$id'
    | '/missions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/certificat'
    | '/connexion'
    | '/inscription'
    | '/missions/$id'
    | '/missions'
  id:
    | '__root__'
    | '/'
    | '/certificat'
    | '/connexion'
    | '/inscription'
    | '/missions'
    | '/missions/$id'
    | '/missions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CertificatRoute: typeof CertificatRoute
  ConnexionRoute: typeof ConnexionRoute
  InscriptionRoute: typeof InscriptionRoute
  MissionsRoute: typeof MissionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/certificat': {
      id: '/certificat'
      path: '/certificat'
      fullPath: '/certificat'
      preLoaderRoute: typeof CertificatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions': {
      id: '/missions'
      path: '/missions'
      fullPath: '/missions'
      preLoaderRoute: typeof MissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/missions/': {
      id: '/missions/'
      path: '/'
      fullPath: '/missions/'
      preLoaderRoute: typeof MissionsIndexRouteImport
      parentRoute: typeof MissionsRoute
    }
    '/missions/$id': {
      id: '/missions/$id'
      path: '/$id'
      fullPath: '/missions/$id'
      preLoaderRoute: typeof MissionsIdRouteImport
      parentRoute: typeof MissionsRoute
    }
  }
}

interface MissionsRouteChildren {
  MissionsIdRoute: typeof MissionsIdRoute
  MissionsIndexRoute: typeof MissionsIndexRoute
}

const MissionsRouteChildren: MissionsRouteChildren = {
  MissionsIdRoute: MissionsIdRoute,
  MissionsIndexRoute: MissionsIndexRoute,
}

const MissionsRouteWithChildren = MissionsRoute._addFileChildren(
  MissionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CertificatRoute: CertificatRoute,
  ConnexionRoute: ConnexionRoute,
  InscriptionRoute: InscriptionRoute,
  MissionsRoute: MissionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
