/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InscriptionRouteImport } from './routes/inscription'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MotDePasseOublieRouteImport } from './routes/mot-de-passe-oublie'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InscriptionRoute = InscriptionRouteImport.update({
  id: '/inscription',
  path: '/inscription',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MotDePasseOublieRoute = MotDePasseOublieRouteImport.update({
  id: '/mot-de-passe-oublie',
  path: '/mot-de-passe-oublie',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/inscription': typeof InscriptionRoute
  '/login': typeof LoginRoute
  '/mot-de-passe-oublie': typeof MotDePasseOublieRoute
  '/reset-password': typeof ResetPasswordRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/inscription' | '/login' | '/mot-de-passe-oublie' | '/reset-password'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/inscription' | '/login' | '/mot-de-passe-oublie' | '/reset-password'
  id:
    | '__root__'
    | '/'
    | '/inscription'
    | '/login'
    | '/mot-de-passe-oublie'
    | '/reset-password'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  InscriptionRoute: typeof InscriptionRoute
  LoginRoute: typeof LoginRoute
  MotDePasseOublieRoute: typeof MotDePasseOublieRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inscription': {
      id: '/inscription'
      path: '/inscription'
      fullPath: '/inscription'
      preLoaderRoute: typeof InscriptionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mot-de-passe-oublie': {
      id: '/mot-de-passe-oublie'
      path: '/mot-de-passe-oublie'
      fullPath: '/mot-de-passe-oublie'
      preLoaderRoute: typeof MotDePasseOublieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  InscriptionRoute: InscriptionRoute,
  LoginRoute: LoginRoute,
  MotDePasseOublieRoute: MotDePasseOublieRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
