spring.application.name=plateforme-benevolat
server.port=8080

# Base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/benevolat_db?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD:}
spring.jpa.open-in-view=false

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT
# Clé secrète HS256 (au moins 32 caractères). A changer en production via variable d'environnement JWT_SECRET
jwt.secret=${JWT_SECRET:benevolat_connect_secret_key_dev_2026_!@#}
# Durée de validité du token JWT en millisecondes (24h)
jwt.expiration.ms=86400000

# Email (OTP / Réinitialisation de mot de passe) - configuration Gmail SMTP
spring.mail.host=${MAIL_HOST:smtp.gmail.com}
spring.mail.port=${MAIL_PORT:587}
spring.mail.username=${MAIL_USERNAME:mohito.raihana@etu.uae.ac.ma}
spring.mail.password=${MAIL_PASSWORD:ezvi sqvn dqyq rble}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Durée de validité de l'OTP (5 minutes)
otp.expiration.minutes=5

# reCAPTCHA Google
recaptcha.secret.key=${RECAPTCHA_SECRET:6LdswuAtAAAAAFOEbfMZZl85bzb9JaE4P01MXWyq}